# Generated by Django 2.2.14 on 2022-10-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodtests', '0002_auto_20221024_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
